spring.application.name=microservice-java

spring.datasource.url=jdbc:postgresql://localhost:5432/subastaya_db
spring.datasource.username=postgres
spring.datasource.password=postgrespassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
