spring.application.name=microservice-java

spring.datasource.url=jdbc:postgresql://localhost:5432/subastaya
spring.datasource.username=postgres
spring.datasource.password=contraDB

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html